# Site settings
title: 2nd Site
# email: yyaazz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is not a blog, no stories or opinions here. Just notes about stuff 
  I fix or find working. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://2nd-site.net" # the base hostname & protocol for your site
twitter_username: jac1nt
github_username:  jcnt
exclude: [temppost.markdown]
timezone: Europe/Budapest
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

gems:
 - jekyll-sitemap

